### ISSUE TITLE
Crash on Map Score Import

### ISSUE THREAD

**Issue by Rekunan** [srb2thepast/osu-alltrick#10] opened 2023-03-20 13:21 UTC
If you input my username and try to import this map: https://osu.ppy.sh/beatmapsets/43466#osu/136400, then it crashes.

I have a hunch that this is due to me having 4 scores (HR, NM, HD, and EZ) on it.

**Comment by Rekunan** [comment] 2023-03-20 13:24
I just encountered the same issue on this map: https://osu.ppy.sh/beatmapsets/55945#osu/169450
This time I have 5 scores on it (HD, HR, EZ, NFDT, EZDT).

I believe you may need to adjust your program to account for having multiple scores.

**Comment by Rekunan** [comment] 2023-03-20 13:26
Considering I just crashed on this map: https://osu.ppy.sh/beatmapsets/25828#osu/106033, I believe the issue is actually not being able to handle old .osu file formats.

**Comment by Rekunan** [comment] 2023-03-20 13:48
Almost forgor the errlog.txt
[errlog.txt](https://github.com/srb2thepast/osu-alltrick/files/11018929/errlog.txt)

**Comment by srb2thepast** [comment] 2023-03-23 00:19
Duplicate of #6: The reason these crashes occurred for each map is related to that the file formats are old, as you mentioned.
I will aim towards fixing this by the next update (v0.88.0).
 
Also, as stated in the readme, when there are multiple scores set on the same map, only the highest score is chosen to be imported.

**Closed by srb2thepast** 2023-03-23 00:19 UTC
